Removed unused `length_tag` variable from `riboviz.demultiplex` `demultiplex` function
This fixes #178 as it removes the line:

```
length_tag = len(barcodes[1])
```

which three

```
IndexError: list index out of range
```

if a sample sheet had 1 barcode.