Fix file name bug in `run_shiny_server.R`
Running `Rscript --vanilla rscripts/run_shiny_server.R` in `develop`, failed with:
```
Error: '/home/ubuntu/riboviz/Mok-simYAL5/output/A/gene_position_length_counts_5start.tsv' does not exist.
Execution halted
```
`gene_position_length_counts_5start.tsv' was renamed to `metagene_position_length_counts_5start.tsv'.
The fix is to change:
```
file_loc <- paste0(x, "/gene_position_length_counts_5start.tsv")
```
to:
```
file_loc <- paste0(x, "/metagene_position_length_counts_5start.tsv")
```